#!/usr/bin/with-contenv bash

# set start function used later
start_mariadb() {
    mariadbd \
        --datadir="${MARIADB_DATADIR}" \
        --pid-file="${MARIADB_PID}" \
        --init-file="${TEMP_SQL_FILE}" \
        --user=grimmory \
        &

    pid="$!"
    RET=1
    while [[ ${RET} -ne 0 ]]; do
        mariadb -uroot -e "status" >/dev/null 2>&1
        RET=$?
        sleep 1
    done
}

# test for existence of mysql folder in datadir and start initialise if not present
if [[ ! -d "${MARIADB_DATADIR}/mysql" ]]; then

    # load env file if it exists
    if [[ -f "/config/env" ]]; then
        # shellcheck source=/dev/null
        source /config/env
    fi

    # make temp sql init file
    TEMP_SQL_FILE=$(mktemp)
    
    # Ensure everyone can read the SQL file
    chmod -R o+r "${TEMP_SQL_FILE}"

    # set basic sql command
    cat >"${TEMP_SQL_FILE}" <<-EOSQL
DELETE FROM mysql.user WHERE user <> 'mariadb.sys' AND user <> 'root';
EOSQL

    if [[ "${#MARIADB_ROOT_PASSWORD}" -lt "4" ]]; then
        SQL_PASS="CREATE USER 'root'@'%' IDENTIFIED BY '' ;"
    else
        SQL_PASS="CREATE USER 'root'@'%' IDENTIFIED BY '${MARIADB_ROOT_PASSWORD}' ;"
    fi

    # Make sure all user and database settings are set and pass is more than 4 characters
    # At the end change to default database created with environment variables to run init and remote scripts there
    if [[ "${MARIADB_USER+x}" ]] &&
        [[ "${MARIADB_DATABASE+x}" ]] &&
        [[ "${MARIADB_PASSWORD+x}" ]] &&
        [[ "${#MARIADB_PASSWORD}" -gt "3" ]]; then
        read -r -d '' SQL_DB_SETUP <<-EOM
CREATE DATABASE \`${MARIADB_DATABASE}\`;
CREATE USER '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL PRIVILEGES ON \`${MARIADB_DATABASE}\`.* TO '${MARIADB_USER}'@'%';
USE \`${MARIADB_DATABASE}\`;
EOM
    fi

    # add rest of sql commands based on password set or not
    cat >>"${TEMP_SQL_FILE}" <<-EONEWSQL
$SQL_PASS
GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
DROP DATABASE IF EXISTS test ;
$SQL_DB_SETUP
EONEWSQL

    echo "Setting Up Initial Databases"

    # add all sql from a user defined directory on first init
    if [[ -e "/config/initdb.d" ]] && [[ -n "$(/bin/ls -A /config/initdb.d/*.sql 2>/dev/null)" ]]; then
        cat /config/initdb.d/*.sql >>"${TEMP_SQL_FILE}"
    fi

    # initialise database structure
    mariadb-install-db --datadir="${MARIADB_DATADIR}" \
        --user=grimmory \
        --auth-root-authentication-method=normal

    # start mariadb and apply our sql commands we set above
    start_mariadb

    # shut down after apply sql commands, waiting for pid to stop
    mariadb-admin -u root shutdown
    echo "SHUTTING DOWN"
    wait "${pid}"
    echo "Database Setup Completed"

    # display a message about password if not set or too short
    if [[ "${#MARIADB_ROOT_PASSWORD}" -lt "4" ]]; then
        cat <<-EOFPASS



#################################################################
# No root password or too short a password, min of 4 characters #
#    No root password will be set, this is not a good thing     #
#   You shoud set one after initialisation with the commands:   #
#                           mariadb                             #
#      ALTER USER 'root'@'%' IDENTIFIED BY 'MyN3wP4ssw0rd';     #
#                      flush privileges;                        #
#################################################################



EOFPASS

        sleep 5s
    fi

    # clean up any old install files from /tmp
    rm -f "${TEMP_SQL_FILE}"
fi

# own the folder the pid for mariadb runs in
# chown -R grimmory:grimmory /databases
