#!/usr/bin/with-contenv bash

s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 3306" \
    s6-setuidgid grimmory \
    /usr/bin/mariadbd-safe \
    --defaults-extra-file="${MARIADB_DATADIR}/custom.cnf" \
    --datadir="${MARIADB_DATADIR}" \
    --pid-file="${MARIADB_PID}" \
    --skip-networking=OFF ${MARIADB_CLI_OPTS}