#!/bin/bash
export HOME=/config
export PWD=/config

export DATABASE_URL=jdbc:mariadb://localhost:3306/${MARIADB_DATABASE:-grimmory}
export DATABASE_USERNAME=${MARIADB_USER:-grimmory}
export DATABASE_PASSWORD=${MARIADB_PASSWORD:-grimmory}

export JAVA_TOOL_OPTIONS="-XX:+UseShenandoahGC \
    -XX:ShenandoahGCHeuristics=compact \
    -XX:+UseCompactObjectHeaders \
    -XX:MaxRAMPercentage=60.0 \
    -XX:InitialRAMPercentage=8.0 \
    -XX:+ExitOnOutOfMemoryError \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath=/tmp/heapdump.hprof \
    -XX:MaxMetaspaceSize=256m \
    -XX:ReservedCodeCacheSize=48m \
    -Xss512k \
    -XX:CICompilerCount=2 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+UseStringDeduplication \
    -XX:ShenandoahUncommitDelay=5000 \
    -XX:ShenandoahGuaranteedGCInterval=30000 \
    -XX:MaxDirectMemorySize=256m"

s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 6060" \
    s6-setuidgid grimmory \
    java \
    --enable-native-access=ALL-UNNAMED \
    --enable-preview \
    -jar /app/app.jar
